language: cpp
dist: xenial
sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake
      - clang
      - mpich
      - libmpich-dev
      - pkg-config
      - libblas-dev
      - liblapack-dev
      - libeigen3-dev
      - libxml2-dev
      - python-dev
      - python-numpy
cache:
  directories:
    - $LOCAL_INSTALL

env:
  global:
    - HWLOC_HIDE_ERRORS=1
    - PRECICE_ROOT="$TRAVIS_BUILD_DIR"
    - LOCAL_INSTALL="$HOME/local"
    - PETSC_ARCH=arch-linux2-c-debug
    - PETSC_DIR=$LOCAL_INSTALL/petsc
    - BOOST_ROOT=$LOCAL_INSTALL

  matrix:
    - MPI=on PETSC=on
    - MPI=on PETSC=off
    - MPI=off PETSC=off


before_install:
  - if [ "$MPI" = "on" ]; then export CXX="mpicxx"; fi

install:
  - $TRAVIS_BUILD_DIR/tools/travis-install-dependencies.sh $LOCAL_INSTALL

before_script:
  - mkdir $TRAVIS_BUILD_DIR/tests

script:
  - cd $TRAVIS_BUILD_DIR
  - cmake $PRECICE_ROOT
  - make -j 2
  - cd tests
  - if [ "$MPI" = "off" ]; then ../build/testprecice -x -r detailed > boost-test-output; fi
  - if [ "$MPI" = "on"  ]; then mpirun -n 4 ../build/testprecice -x -r detailed > boost-test-output 2> boost-test-error; fi

after_failure:
  - cd $TRAVIS_BUILD_DIR
  - cat config.log
  - cat -n ./tests/boost-test-*
